# Dockerfile
FROM python:3.10.6

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG PG_DATABASE_URL
ARG SECRET_KEY
ARG ALGORITHM
ARG ACCESS_TOKEN_EXPIRE_MINUTES
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG S3_BUCKET_NAME
ARG PINECONE_API_KEY
ARG UNSTRUCTURED_API_KEY
ARG GOOGLE_API_KEY

ENV PG_DATABASE_URL = $PG_DATABASE_URL 
ENV SECRET_KEY = $SECRET_KEY 
ENV ALGORITHM = $ALGORITHM 
ENV ACCESS_TOKEN_EXPIRE_MINUTES = $ACCESS_TOKEN_EXPIRE_MINUTES 
ENV AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID 
ENV AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY 
ENV S3_BUCKET_NAME = $S3_BUCKET_NAME 
ENV PINECONE_API_KEY = $PINECONE_API_KEY 
ENV UNSTRUCTURED_API_KEY = $UNSTRUCTURED_API_KEY 
ENV GOOGLE_API_KEY = $GOOGLE_API_KEY 

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]